FROM ruby:2.7.2

WORKDIR /home/app

ENV PORT 3000

EXPOSE $PORT

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN apt-get install -y default-mysql-client

RUN gem install rails bundler
RUN gem install rails
COPY Gemfile /home/app/Gemfile
COPY Gemfile.lock /home/app/Gemfile.lock
RUN bundle install
COPY . /home/app

